# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1n6dhegKm5ZGUHSX0kwWYSr345Ez4E9

# ***Lab Task 1: Student Grade Calculator***
"""

marks = int(input("Enter marks (1-100): "))

if marks < 1 or marks > 100:
    print("Invalid input")
elif marks < 50:
    print("Grade: F")
elif marks <= 60:
    print("Grade: E")
elif marks <= 70:
    print("Grade: D")
elif marks <= 80:
    print("Grade: C")
elif marks <= 90:
    print("Grade: B")
else:
    print("Grade: A")

"""# **Lab Task 2: Factorial Calculator**"""

num = int(input("Enter a number: "))

if num < 0:
    print("Invalid input")
else:
    fact = 1
    for i in range(1, num + 1):
        fact = fact * i
    print("Factorial is:", fact)

"""# ***Lab Task 3: Fibonacci Series***"""

n = int(input("Enter number of terms: "))

if n <= 0:
    print("Invalid input")
else:
    a = 0
    b = 1
    for i in range(n):
        print(a, end=" ")
        c = a + b
        a = b
        b = c